"""Unit tests for the pitch homography -> ground-plane velocity module
(INC-2b / ADAAAA-4326, slice 3).

The acceptance target for this slice: per-frame ball bbox displacement converts
to ground-plane m/s with speed error <= 15% vs hand-labeled reference. We build
a synthetic broadcast-style camera: pick a set of real field points (pitch
rectangle + goal frame), define an image->field homography H, generate on-pitch
ball motion at a KNOWN speed, project it into image space, add realistic box
jitter, and check the estimator recovers the speed within the 15% budget.

Also verifies the homography math itself (DLT round-trip on corner
correspondences) and the image-space fallback path.
"""
import numpy as np
import pytest

from app.pitch_homography import (
    BallVelocityEstimator,
    estimate_homography,
    homography_from_pitch_rect,
    project_ball_center,
    project_points,
)

# Billboard-style broadcast camera over a standard pitch (105 x 68 m).
# Field coords: X width (0..68), Y length (0..105). Image: 1280 x 720 px.
FIELD_CORNERS = [
    (0.0, 0.0),
    (68.0, 0.0),    # wide bottom of frame (near camera)
    (0.0, 105.0),
    (68.0, 105.0),  # far from the camera
]
# Corresponding image-space corners (perspective: near edge is wide/low,
# far edge is narrow/high). Consistent ordering with FIELD_CORNERS.
IMAGE_CORNERS = [
    (120.0, 680.0),
    (1160.0, 680.0),
    (430.0, 90.0),
    (850.0, 90.0),
]
# A second set of reference points (goal-frame / line intersections) for a
# richer, more robust fit: the two goal lines + halfway line samples.
GOAL_FRAME_REF = [
    (0.0, 0.0), (68.0, 0.0),
    (0.0, 105.0), (68.0, 105.0),
    (34.0, 5.0), (34.0, 100.0),  # halfway-ish line sample
    (5.0, 52.0), (63.0, 52.0),   # halfway line across the width
]

FIELD_REF = [
    (0.0, 0.0), (68.0, 0.0), (0.0, 105.0), (68.0, 105.0),
    (34.0, 5.0), (34.0, 100.0), (5.0, 52.0), (63.0, 52.0),
]
# Image positions for the SAME reference points, generated by projecting the
# field points through a synthetic camera (field->image H). Deriving them this
# way (rather than hand-placing them) guarantees they are exactly
# projective-consistent, so the DLT round-trip test validates the math.
_CAMERA_IF = estimate_homography(IMAGE_CORNERS, FIELD_CORNERS)  # image->field
_CAMERA_FI = np.linalg.inv(_CAMERA_IF)  # field->image
IMAGE_REF = [tuple(p) for p in project_points(_CAMERA_FI, FIELD_REF)]

FPS = 60
DT = 1.0 / FPS


def _known_homography() -> np.ndarray:
    """image->field H built from the synthetic corner correspondences."""
    return estimate_homography(IMAGE_REF, FIELD_REF)


def _image_pos(fields: np.ndarray, H_if: np.ndarray) -> np.ndarray:
    """Project field points -> image points using the inverse (field->image) H.

    We fit H_if = image->field with estimate_homography, so field->image is
    its inverse (up to scale). Return (N,2) image pixels.
    """
    H_fi = np.linalg.inv(H_if)
    return project_points(H_fi, fields)


def test_dlt_roundtrip_recovers_corners():
    """DLT image->field H maps the fit reference points back to their field
    coords (self-consistency of the homography math)."""
    H = _known_homography()
    out = project_points(H, IMAGE_REF)
    err = np.linalg.norm(out - np.array(FIELD_REF), axis=1)
    assert np.max(err) < 1e-6, f"corner round-trip error too large: {err}"


def test_homography_from_pitch_rect_matches_corners():
    """homography_from_pitch_rect (pure 4-corner calibration) recovers the
    on-pitch coordinates of those corners exactly."""
    H = homography_from_pitch_rect(IMAGE_CORNERS, FIELD_CORNERS)
    out = project_points(H, IMAGE_CORNERS)
    err = np.linalg.norm(out - np.array(FIELD_CORNERS), axis=1)
    assert np.max(err) < 1e-6


def test_project_ball_center_uses_bbox_center():
    H = _known_homography()
    # A zero-area box centered at a known image point -> that field point.
    ix, iy = 620.0, 620.0
    fx, fy = project_points(H, [(ix, iy)])[0]
    got = project_ball_center(H, (ix - 3, iy - 3, ix + 3, iy + 3))
    assert abs(got[0] - fx) < 1e-9 and abs(got[1] - fy) < 1e-9


def test_speed_error_within_15pct_on_known_motion():
    """REQUIRED: ground-plane speed error <= 15% vs a hand-labeled constant
    on-pitch speed, with realistic ball-box jitter under perspective."""
    H = _known_homography()
    est = BallVelocityEstimator(H, window=6)

    v = np.array([12.0, 5.0])  # known on-pitch velocity, m/s
    speed_true = float(np.linalg.norm(v))
    start = np.array([10.0, 20.0])
    n = 45
    rng = np.random.default_rng(3)

    speeds = []
    for k in range(n):
        field = start + v * (k * DT)
        img = _image_pos(field[None, :], H)[0] + rng.normal(0, 0.4, 2)
        # small ball box around the center (a few px wide)
        bbox = (img[0] - 4, img[1] - 4, img[0] + 4, img[1] + 4)
        bv = est.update(bbox, ts=k * DT)
        if bv is not None:
            speeds.append(bv.speedMps)

    assert len(speeds) >= 30, "estimator should report across most of the run"
    # Last estimate is the steady-state one (window fully populated and warm).
    final = speeds[-1]
    err = abs(final - speed_true) / speed_true
    assert err <= 0.15, (
        f"speed error {err:.3f} exceeds 15% budget "
        f"(got {final:.2f} m/s, true {speed_true:.2f} m/s)"
    )


def test_velocity_components_and_homography_flag():
    """vx/vy match the known motion direction; homography=True and field
    position is on-pitch meters."""
    H = _known_homography()
    est = BallVelocityEstimator(H, window=4)
    v = np.array([14.0, -6.0])
    start = np.array([5.0, 30.0])
    n = 40
    last = None
    for k in range(n):
        field = start + v * (k * DT)
        img = _image_pos(field[None, :], H)[0]
        bbox = (img[0] - 5, img[1] - 5, img[0] + 5, img[1] + 5)
        last = est.update(bbox, ts=k * DT)
    assert last is not None
    assert last.homography is True
    assert last.speedMps <= 20.0
    assert abs(last.vxMps - v[0]) / abs(v[0]) < 0.20
    assert abs(last.vyMps - v[1]) / abs(v[1]) < 0.20
    # Field position is on-pitch (within the pitch rectangle).
    assert 0.0 <= last.posXm <= 68.0
    assert 0.0 <= last.posYm <= 105.0


def test_image_space_fallback_when_no_homography():
    """Without a calibration, the estimator still returns a velocity but flags
    homography=False (image-space px/step, not meters) and never crashes."""
    est = BallVelocityEstimator(H=None, window=3)
    last = None
    for k in range(30):
        cx = 200.0 + 30.0 * k
        bbox = (cx - 4, 300.0, cx + 4, 308.0)
        last = est.update(bbox, ts=k * DT)
    assert last is not None
    assert last.homography is False


def test_requires_at_least_4_correspondences():
    with pytest.raises(ValueError):
        estimate_homography([(0, 0), (1, 1), (2, 2)], [(0, 0), (1, 1), (2, 2)])


def test_degenerate_bbox_returns_none():
    est = BallVelocityEstimator(_known_homography())
    assert est.update((10, 10, 10, 10), ts=1.0) is None
